
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./staticfiles/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:80"
    networks:
      - backend
      - payment-processor
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10MB"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api1: &api
    build: ./backend
    container_name: rinha-api1
    hostname: api1
    env_file:
      - .env
    environment:
      - INSTANCE_ID=API-1
      - REDIS_HOST=rinha-redis
      - REDIS_PORT=6379
    command: ["node", "dist/server.js"]   # ou src/server.js se estiver rodando TS direto
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "96MB"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api2:
    <<: *api
    container_name: rinha-api2
    hostname: api2
    environment:
      - INSTANCE_ID=API-2
      - REDIS_HOST=rinha-redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure:5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128MB"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

